# Configuración del proyecto
project:
  name: "tscdia-pp"
  version: "1.0.0"
  description: "Práctica Profesionalizante - Tecnicatura Superior en Ciencia de Datos e IA"

# Rutas de datos
data:
  raw: "data/raw/"
  processed: "data/processed/"
  external: "data/external/"

# Configuración de modelos
model:
  random_state: 42
  test_size: 0.2
  validation_size: 0.2

# Configuración de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Configuración de visualización
plots:
  figsize: [10, 6]
  style: "seaborn-v0_8"
  dpi: 300

# Configuración de Spark
spark:
  app_name: "TSCDIA-MySQL-Processing"
  master: "local[*]"  # local[*] para usar todos los cores disponibles
  executor_memory: "4g"
  driver_memory: "2g"
  max_result_size: "2g"
  sql_adaptive_enabled: true
  sql_adaptive_coalesce_partitions_enabled: true
  # Configuración específica para MySQL
  mysql_jar_packages: "mysql:mysql-connector-java:8.0.33"
  driver_extra_class_path: ""

# Configuración de bases de datos - MySQL Principal
databases:
  mysql:
    # Configuración principal de MySQL
    host: "localhost"
    port: 3306
    database: "tscdia_db"
    user: "your_username"
    password: "your_password"
    driver: "com.mysql.cj.jdbc.Driver"
    
    # URL completa (se construye automáticamente)
    url: "jdbc:mysql://localhost:3306/tscdia_db"
    
    # Opciones de conexión MySQL
    connection_options:
      useSSL: false
      allowPublicKeyRetrieval: true
      serverTimezone: "UTC"
      characterEncoding: "utf8"
      useUnicode: true
      autoReconnect: true
      failOverReadOnly: false
      maxReconnects: 3
      
    # Configuración de performance
    performance:
      fetchSize: 1000
      batchSize: 1000
      queryTimeout: 3600
      connectionTimeout: 30000
      socketTimeout: 60000
